# Generated by Django 6.0.7 on 2026-07-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OccupancyRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.BigIntegerField()),
                ('ts_recv', models.BigIntegerField()),
                ('device_id', models.CharField(max_length=40)),
                ('room', models.CharField(max_length=50)),
                ('seq', models.BigIntegerField()),
                ('count', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['device_id', 'ts'], name='events_occu_device__790511_idx')],
                'constraints': [models.UniqueConstraint(fields=('device_id', 'seq'), name='uq_occ_seq')],
            },
        ),
        migrations.CreateModel(
            name='PostureRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.BigIntegerField()),
                ('ts_recv', models.BigIntegerField()),
                ('device_id', models.CharField(max_length=40)),
                ('room', models.CharField(max_length=50)),
                ('seq', models.BigIntegerField()),
                ('posture', models.CharField(max_length=10)),
                ('confidence', models.FloatField()),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['device_id', 'ts'], name='events_post_device__05cc96_idx')],
                'constraints': [models.UniqueConstraint(fields=('device_id', 'seq'), name='uq_posture_seq')],
            },
        ),
        migrations.CreateModel(
            name='PresenceRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.BigIntegerField()),
                ('ts_recv', models.BigIntegerField()),
                ('device_id', models.CharField(max_length=40)),
                ('room', models.CharField(max_length=50)),
                ('seq', models.BigIntegerField()),
                ('presence', models.BooleanField()),
                ('moving', models.BooleanField()),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['device_id', 'ts'], name='events_pres_device__a894e6_idx')],
                'constraints': [models.UniqueConstraint(fields=('device_id', 'seq'), name='uq_presence_seq')],
            },
        ),
        migrations.CreateModel(
            name='VitalRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.BigIntegerField()),
                ('ts_recv', models.BigIntegerField()),
                ('device_id', models.CharField(max_length=40)),
                ('room', models.CharField(max_length=50)),
                ('seq', models.BigIntegerField()),
                ('quiet', models.BooleanField()),
                ('resp_rate', models.FloatField(null=True)),
                ('heart_rate', models.FloatField(null=True)),
                ('quality', models.FloatField()),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['device_id', 'ts'], name='events_vita_device__f1200d_idx')],
                'constraints': [models.UniqueConstraint(fields=('device_id', 'seq'), name='uq_vital_seq')],
            },
        ),
    ]
