# Generated by Django 6.0.7 on 2026-07-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_hypertables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=40)),
                ('room', models.CharField(max_length=50)),
                ('ts', models.BigIntegerField()),
                ('ts_recv', models.BigIntegerField()),
                ('alert_type', models.CharField(max_length=30)),
                ('severity', models.CharField(max_length=10)),
                ('payload', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='RoomState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=40, unique=True)),
                ('room', models.CharField(max_length=50)),
                ('ts', models.BigIntegerField(help_text='latest decoder output ts, UTC ms')),
                ('ts_recv', models.BigIntegerField()),
                ('posture', models.CharField(blank=True, max_length=10, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('presence', models.BooleanField(default=True)),
                ('moving', models.BooleanField(default=False)),
                ('resp_rate', models.FloatField(blank=True, null=True)),
                ('heart_rate', models.FloatField(blank=True, null=True)),
                ('quality', models.FloatField(blank=True, null=True)),
                ('anomaly_score', models.FloatField(default=0.0)),
                ('occupancy_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=40)),
                ('room', models.CharField(max_length=50)),
                ('ts', models.BigIntegerField()),
                ('state_blob', models.JSONField()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='occupancyrow',
            name='events_occu_device__790511_idx',
        ),
        migrations.RemoveConstraint(
            model_name='occupancyrow',
            name='uq_occ_seq',
        ),
        migrations.DeleteModel(
            name='OccupancyRow',
        ),
        migrations.RemoveIndex(
            model_name='posturerow',
            name='events_post_device__05cc96_idx',
        ),
        migrations.RemoveConstraint(
            model_name='posturerow',
            name='uq_posture_seq',
        ),
        migrations.DeleteModel(
            name='PostureRow',
        ),
        migrations.RemoveIndex(
            model_name='presencerow',
            name='events_pres_device__a894e6_idx',
        ),
        migrations.RemoveConstraint(
            model_name='presencerow',
            name='uq_presence_seq',
        ),
        migrations.DeleteModel(
            name='PresenceRow',
        ),
        migrations.RemoveIndex(
            model_name='vitalrow',
            name='events_vita_device__f1200d_idx',
        ),
        migrations.RemoveConstraint(
            model_name='vitalrow',
            name='uq_vital_seq',
        ),
        migrations.DeleteModel(
            name='VitalRow',
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['device_id', 'ts'], name='events_aler_device__f47ec2_idx'),
        ),
        migrations.AddIndex(
            model_name='roomstate',
            index=models.Index(fields=['device_id'], name='events_room_device__546063_idx'),
        ),
        migrations.AddIndex(
            model_name='statesnapshot',
            index=models.Index(fields=['device_id', 'ts'], name='events_stat_device__98fa94_idx'),
        ),
    ]
