# Generated by Django 6.0.7 on 2026-07-12 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadarDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=40, unique=True)),
                ('secret', models.CharField(max_length=64)),
                ('room', models.CharField(max_length=50)),
                ('online', models.BooleanField(default=False)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('fw_version', models.CharField(default='sim-0.1', max_length=20)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='families.family')),
            ],
        ),
    ]
